-- init.lua
require("core.keymaps")
require("core.options")
require("plugin.lazy-config")
require("core.colorscheme")
require("plugin.lualine-config")
require("plugin.whichkey")
require("plugin.neotree-config")
require("plugin.telescope-config")
require("plugin.alpha-dash-config")
require("plugin.treesitter-config")
require("plugin.lsp-config")
require("plugin.toggleterm-config")
require("plugin.autopairs-config")
require("plugin.undotree-config")
require("plugin.indentline-config")
require("plugin.gitsigns-config")
require("plugin.bufferline-config")
require("plugin.lspkind-config")
require("plugin.todocomments-config")
--require("plugin.nvim-dap-ui-config")
require("plugin.goto-preview-config")
require("plugin.none-ls")
require("plugin.completions")
--require("plugin.nvim-dap-virtual-text-config")
-- Language
require("lang.java")
require("lang.go")
